apiVersion: v1
kind: Service
metadata:
  name: pghc-postgres
  namespace: pghc
  labels:
    app: postgres-repl
spec:
  selector:
    app: postgres-repl
  clusterIP: None
  ports:
  - port: 5432
    name: postgresql