apiVersion: v1
kind: Service
metadata:
  name: pghc-backend-dns
  namespace: pghc
  labels:
    app: pghc-backend
spec:
  selector:
    app: pghc-backend
  clusterIP: None
  ports:
  - port: 8080
    name: nodejs
  - port: 9228
    name: nodejs-debug