---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pghc-backend
  namespace: pghc
spec:
  selector:
    matchLabels:
      app: pghc-backend
  serviceName: pghc-postgres-dns
  replicas: 6
  template:
    metadata:
      labels:
        app: pghc-backend
      namespace: pghc
    spec:
      containers:
      - name: pghc-backend
        image: pghc-backend
        imagePullPolicy: Never
