---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pghc-backend
  namespace: pghc
spec:
  selector:
    matchLabels:
      app: pghc-backend
  serviceName: pghc-backend-dns
  replicas: 2
  template:
    metadata:
      labels:
        app: pghc-backend
      namespace: pghc
    spec:
      containers:
      - name: pghc-backend
        image: sikanrong101/pghc-backend:latest
